### PR TITLE
License

### PR DESCRIPTION
**Pull request by nikhilm**
@treeder

### CODE REVIEW

**Comment by nikhilm** [comment]
@treeder Please review but DO NOT MERGE until the underlying PR is reviewed. Thanks.

**Comment by treeder** [comment]
I don't think we need the license in every file, just the single license file is enough. Just adds clutter.

**Comment by nikhilm** [comment]
http://www.apache.org/dev/apply-license.html#copy-per-file
You are right

Nikhil
--
Sent from a tiny keyboard.




On Thu, Apr 7, 2016 at 5:46 AM -0700, "Travis Reeder" <notifications@github.com> wrote:












I don't think we need the license in every file, just the single license file is enough. Just adds clutter.

**Comment by nikhilm** [comment]
This is ready.

**Pull request merged**
